# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='image',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='intro',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
