# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161022_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='image',
        ),
    ]
