# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-15 21:20
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161115_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
